server:
  port: 8081
  servlet:
    context-path: /mqtest

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: false
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 15

