eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.162:8761/eureka/
  instance:
    prefer-ip-address: true
    #instance-id: 192.168.3.162:8764
server:
  port: 8764
spring:
  application:
    name: service-ribbon
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.web: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
